import os
from supabase import create_client, Client

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://wttssbxoptowkxdjtuky.supabase.co")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dHNzYnhvcHRvd2t4ZGp0dWt5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzc1NTg4NiwiZXhwIjoyMDg5MzMxODg2fQ.rGnrPaL3alNpMLsTjji5RKumpEYD5MJtb-fkbu78tOg")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# SQL Commands to initialize the Supabase PostgreSQL database tables
SETUP_SQL = """
-- Create USERS table with profile fields
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    hashed_password TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'patient',
    height FLOAT DEFAULT 0,
    weight FLOAT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create HEALTH_RECORDS table 
CREATE TABLE IF NOT EXISTS public.health_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    image_path TEXT NOT NULL,
    prediction_result TEXT NOT NULL,
    confidence FLOAT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT
);

-- Create SYMPTOMS table
CREATE TABLE IF NOT EXISTS public.symptoms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    symptom_name TEXT NOT NULL,
    severity INTEGER DEFAULT 1,
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    notes TEXT
);

-- Create MESSAGES table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    receiver_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create APPOINTMENTS table
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    doctor_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    appointment_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
"""

print("Please run the following SQL commands in your Supabase SQL Editor manually:\n")
print(SETUP_SQL)
print("\n---")
print("After running these commands, your Supabase Database will be ready to link with the FastAPI app!")
